import { StrictMode, useState } from "react"
import { createRoot } from "react-dom/client"
import { QueryClient, QueryClientProvider, useQuery } from "@tanstack/react-query"
import { api, formatTime, Message } from "../shared/api"
import "../shared/styles.css"
import "./style.css"

const client = new QueryClient()
function Conversation({id,preview,count,last}:{id:number;preview:string;count:number;last:string}){const [open,setOpen]=useState(false);const detail=useQuery({enabled:open,queryKey:["my-conversation",id],queryFn:()=>api<{messages:Message[]}>(`/api/me/conversations/${id}`)});return <article className="card conversation"><button onClick={()=>setOpen(v=>!v)}><span>{preview||"客服会话"}</span><small>{count} 条 · {formatTime(last)}</small></button>{open&&<div className="detail">{detail.isLoading?"加载中…":detail.error?"加载失败":detail.data!.messages.map((m,i)=><div key={i} className={`portal-message ${m.sender_type}`}><small>{m.sender_type==="customer"?"我":"AI 客服"} · {formatTime(m.occurred_at)}</small><div>{m.content}</div></div>)}</div>}</article>}
function App(){const profile=useQuery({queryKey:["me"],queryFn:()=>api<{profile:{nickname:string;avatar_url:string;gender:number};data_scope:string}>("/api/me")});const conversations=useQuery({queryKey:["my-conversations"],queryFn:()=>api<{conversations:{id:number;preview:string;message_count:number;last_message_at:string}[]}>("/api/me/conversations")});if(profile.isLoading||conversations.isLoading)return <main className="portal"><div className="card">加载中…</div></main>;if(profile.error||conversations.error)return <main className="portal"><div className="card error">登录已失效，请返回微信客服重新获取链接。</div></main>;const p=profile.data!.profile;return <main className="portal"><section className="card profile"><div className="portal-avatar">{p.nickname.slice(0,1)||"微"}</div><div><h1>{p.nickname||"微信用户"}</h1><p>我的 AI 客服记录</p></div></section><div className="notice">{profile.data!.data_scope}</div><h2>历史对话</h2>{conversations.data!.conversations.length?conversations.data!.conversations.map(c=><Conversation key={c.id} id={c.id} preview={c.preview} count={c.message_count} last={c.last_message_at}/>):<div className="card muted">还没有客服记录</div>}<footer>本页面仅展示本系统收到的微信客服消息。</footer></main>}
createRoot(document.getElementById("root")!).render(<StrictMode><QueryClientProvider client={client}><App/></QueryClientProvider></StrictMode>)
