"""Small dependency-free customer-service operator console."""

from __future__ import annotations


def render_admin_console() -> str:
    return """<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>客服后台 Demo</title><style>
:root{font-family:system-ui,-apple-system,"Segoe UI",sans-serif;color:#17202a;background:#f4f6f8}*{box-sizing:border-box}body{margin:0;height:100vh;overflow:hidden}.app{display:grid;grid-template-columns:280px minmax(420px,1fr) 280px;height:100vh}.panel{background:#fff;border-right:1px solid #e5e7eb;min-width:0}.users{display:flex;flex-direction:column}.head{padding:18px;border-bottom:1px solid #e5e7eb}.head h1{font-size:18px;margin:0 0 12px}.search{display:flex;gap:6px}.search input{width:100%;padding:9px;border:1px solid #d6dbe1;border-radius:8px}.user-list{overflow:auto}.user{display:grid;grid-template-columns:42px 1fr auto;gap:9px;padding:12px 14px;border-bottom:1px solid #f0f1f3;cursor:pointer}.user.active{background:#e9f5ff}.avatar{width:42px;height:42px;border-radius:50%;object-fit:cover;background:#dbe4ec}.user-name{font-weight:650;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.preview{font-size:12px;color:#667085;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;margin-top:4px}.meta{font-size:11px;color:#98a2b3;text-align:right}.badge{display:inline-block;background:#f04438;color:white;border-radius:999px;padding:1px 6px;font-size:11px;margin-top:5px}.chat{display:flex;flex-direction:column;background:#f8fafc}.chat-head{padding:16px 20px;background:#fff;border-bottom:1px solid #e5e7eb;font-weight:650}.messages{flex:1;overflow:auto;padding:20px}.msg{display:flex;margin:10px 0}.msg.user{justify-content:flex-start}.msg.ai,.msg.human_agent{justify-content:flex-end}.bubble{max-width:75%;padding:10px 13px;border-radius:12px;background:#fff;box-shadow:0 1px 2px #00000012;white-space:pre-wrap;word-break:break-word}.ai .bubble{background:#e9f5ff}.human_agent .bubble{background:#d9fdd3}.failed .bubble{border:1px solid #f04438}.msg small{display:block;color:#98a2b3;font-size:10px;margin-top:5px}.composer{padding:12px;background:#fff;border-top:1px solid #e5e7eb}.composer textarea{width:100%;resize:none;padding:10px;border:1px solid #d6dbe1;border-radius:8px}.composer-row{display:flex;justify-content:space-between;margin-top:8px}.btn{border:0;border-radius:8px;padding:8px 14px;background:#1677ff;color:#fff;cursor:pointer}.btn:disabled{opacity:.5;cursor:not-allowed}.load-more{display:block;margin:0 auto 8px}.info{padding:20px}.info h2{font-size:17px;margin-top:0}.info dt{font-size:12px;color:#667085;margin-top:14px}.info dd{margin:3px 0;word-break:break-word}.empty{padding:30px;text-align:center;color:#98a2b3}.error{color:#b42318;padding:12px;font-size:13px}@media(max-width:900px){.app{grid-template-columns:240px 1fr}.info{display:none}}@media(max-width:620px){.app{grid-template-columns:1fr}.users{display:none}.chat{display:flex}.chat.no-user{display:none}}
</style></head><body><main class="app"><section class="panel users"><div class="head"><h1>客服后台 Demo</h1><div class="search"><input id="search" placeholder="搜索昵称或用户 ID"><button class="btn" id="refresh">刷新</button></div></div><div id="users" class="user-list"><div class="empty">加载中…</div></div></section><section class="chat no-user" id="chat"><div class="chat-head" id="chat-head">选择一个用户开始会话</div><div class="messages" id="messages"><div class="empty">暂无会话</div></div><div class="composer"><textarea id="input" rows="3" maxlength="2000" placeholder="输入消息，Enter 发送，Shift+Enter 换行" disabled></textarea><div class="composer-row"><small id="send-state"></small><button class="btn" id="send" disabled>发送</button></div></div></section><aside class="panel info" id="info"><h2>用户信息</h2><div class="empty">选择用户后显示</div></aside></main><script>
const $=s=>document.querySelector(s);let state={users:[],user:null,before:null,loading:false};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const time=t=>t?new Date(typeof t==='number'?t*1000:t).toLocaleString():'';
async function api(url,opt){const r=await fetch(url,opt);let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error?.message||'请求失败');return d}
async function loadUsers(){try{const q=encodeURIComponent($('#search').value.trim());const d=await api('/api/admin/users?q='+q+'&page_size=100');state.users=d.users;renderUsers()}catch(e){$('#users').innerHTML='<div class="error">'+esc(e.message)+'</div>'}}
function renderUsers(){$('#users').innerHTML=state.users.length?state.users.map(u=>`<div class="user ${state.user&&state.user.id===u.id?'active':''}" data-id="${u.id}"><img class="avatar" src="${esc(u.avatar_url||'')}" onerror="this.style.visibility='hidden'"><div><div class="user-name">${esc(u.nickname||'未命名用户')}</div><div class="preview">${esc(u.last_message_preview||'暂无消息')}</div></div><div class="meta">${time(u.last_active_at)}${u.unread_count?`<br><span class="badge">${u.unread_count}</span>`:''}</div></div>`).join(''):'<div class="empty">暂无用户</div>';document.querySelectorAll('.user').forEach(x=>x.onclick=()=>selectUser(Number(x.dataset.id)))}
async function selectUser(id){state.user=state.users.find(x=>x.id===id)||{id};state.before=null;$('#chat').classList.remove('no-user');$('#input').disabled=false;$('#send').disabled=false;renderUsers();await loadUser();await loadMessages()}
async function loadUser(){try{const d=await api('/api/admin/users/'+state.user.id);state.user={...state.user,...d.user};$('#chat-head').textContent=state.user.nickname||'未命名用户';$('#info').innerHTML=`<h2>${esc(state.user.nickname||'未命名用户')}</h2><dl><dt>首次出现</dt><dd>${time(state.user.first_seen_at)}</dd><dt>最近活跃</dt><dd>${time(state.user.last_seen_at)}</dd><dt>性别</dt><dd>${state.user.gender===1?'男':state.user.gender===2?'女':'未知'}</dd><dt>数据范围</dt><dd>仅限本系统收到的客服消息</dd></dl>`}catch(e){$('#info').innerHTML='<div class="error">'+esc(e.message)+'</div>'}}
async function loadMessages(older=false){if(state.loading||!state.user)return;state.loading=true;try{const u='/api/admin/users/'+state.user.id+'/conversation?limit=50'+(older&&state.before?'&before_id='+state.before:'');const d=await api(u);const box=$('#messages');const html=d.messages.map(m=>`<div class="msg ${esc(m.sender_type)} ${m.send_status==='failed'?'failed':''}" data-mid="${m.id}"><div class="bubble">${esc(m.content)}<small>${m.sender_type==='user'?'用户':m.sender_type==='human_agent'?'人工客服':m.sender_type==='ai'?'AI':'系统'} · ${time(m.occurred_at)} · ${esc(m.send_status)}${m.send_status==='failed'?` <button onclick="retry(${m.id})">重试</button>`:''}</small></div></div>`).join('');if(older){box.insertAdjacentHTML('afterbegin',html)}else{box.innerHTML=html||'<div class="empty">暂无会话</div>';box.scrollTop=box.scrollHeight}state.before=d.has_more?d.next_before_id:null;if(d.has_more&&!document.querySelector('.load-more')){box.insertAdjacentHTML('afterbegin','<button class="btn load-more" onclick="loadMessages(true)">加载更早消息</button>')}await loadUsers()}catch(e){$('#messages').innerHTML='<div class="error">'+esc(e.message)+'</div>'}finally{state.loading=false}}
async function send(retryId=null){if(!state.user)return;const content=$('#input').value.trim();if(!retryId&&!content)return;$('#send').disabled=true;$('#send-state').textContent='发送中…';try{const body=retryId?{content:'',retry_message_id:retryId,request_id:crypto.randomUUID()}:{content,request_id:crypto.randomUUID()};await api('/api/admin/users/'+state.user.id+'/messages',{method:'POST',headers:{'content-type':'application/json','x-requested-with':'XMLHttpRequest'},body:JSON.stringify(body)});$('#input').value='';await loadMessages();$('#send-state').textContent='已发送'}catch(e){$('#send-state').textContent=e.message;await loadMessages()}finally{$('#send').disabled=false}}
async function retry(id){await send(id)}$('#send').onclick=()=>send();$('#refresh').onclick=loadUsers;$('#search').oninput=()=>{clearTimeout(window._st);window._st=setTimeout(loadUsers,250)};$('#input').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}};loadUsers();
</script></body></html>"""
